/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAnalyzerRouteImport } from './routes/_authenticated/analyzer'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedCoverLetterRouteImport } from './routes/_authenticated/cover-letter'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated/discovery'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTailorRouteImport } from './routes/_authenticated/tailor'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyzerRoute = AuthenticatedAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoverLetterRoute =
  AuthenticatedCoverLetterRouteImport.update({
    id: '/cover-letter',
    path: '/cover-letter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTailorRoute = AuthenticatedTailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/match': typeof AuthenticatedMatchRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tailor': typeof AuthenticatedTailorRoute
  '/tracker': typeof AuthenticatedTrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/match': typeof AuthenticatedMatchRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tailor': typeof AuthenticatedTailorRoute
  '/tracker': typeof AuthenticatedTrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/signup': typeof SignupRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/analyzer': typeof AuthenticatedAnalyzerRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/match': typeof AuthenticatedMatchRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tailor': typeof AuthenticatedTailorRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portfolio'
    | '/signup'
    | '/analytics'
    | '/analyzer'
    | '/automation'
    | '/cover-letter'
    | '/dashboard'
    | '/discovery'
    | '/insights'
    | '/match'
    | '/resumes'
    | '/settings'
    | '/tailor'
    | '/tracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portfolio'
    | '/signup'
    | '/analytics'
    | '/analyzer'
    | '/automation'
    | '/cover-letter'
    | '/dashboard'
    | '/discovery'
    | '/insights'
    | '/match'
    | '/resumes'
    | '/settings'
    | '/tailor'
    | '/tracker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/portfolio'
    | '/signup'
    | '/_authenticated/analytics'
    | '/_authenticated/analyzer'
    | '/_authenticated/automation'
    | '/_authenticated/cover-letter'
    | '/_authenticated/dashboard'
    | '/_authenticated/discovery'
    | '/_authenticated/insights'
    | '/_authenticated/match'
    | '/_authenticated/resumes'
    | '/_authenticated/settings'
    | '/_authenticated/tailor'
    | '/_authenticated/tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyzer': {
      id: '/_authenticated/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AuthenticatedAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cover-letter': {
      id: '/_authenticated/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof AuthenticatedCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tailor': {
      id: '/_authenticated/tailor'
      path: '/tailor'
      fullPath: '/tailor'
      preLoaderRoute: typeof AuthenticatedTailorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnalyzerRoute: typeof AuthenticatedAnalyzerRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedCoverLetterRoute: typeof AuthenticatedCoverLetterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTailorRoute: typeof AuthenticatedTailorRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnalyzerRoute: AuthenticatedAnalyzerRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedCoverLetterRoute: AuthenticatedCoverLetterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMatchRoute: AuthenticatedMatchRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTailorRoute: AuthenticatedTailorRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
